#!/bin/sh -eu

nix run \
    --ignore-environment \
    --file "$(dirname $0)/nix" \
    nix-project-org2gfm \
    nixpkgs.bash \
    nixpkgs.coreutils \
    nixpkgs.gnugrep \
    nixpkgs.gnutar \
    nixpkgs.gzip \
    nixpkgs.procps \
    --command \
    org2gfm \
    --ignore 'setup\.org' \
    --nix "$(command -v nix)" \
    --evaluate \
    "$@"
