#!/bin/sh -eu


PROJECT_ROOT="$(dirname "$0")/.."
LOG_DIR="$PROJECT_ROOT/support/log"


main()
{
    mkdir -p "$LOG_DIR"
    for tutorial in pkgs-make # haskell python
    do
        for command in nix-run licenses docker-image docker-tarball
        do
            "$PROJECT_ROOT/run/nix-package-run" "$command" -t "$tutorial" \
                | tee "$LOG_DIR/$tutorial.$command.docker-unused.log"
            "$PROJECT_ROOT/run/nix-package-run" "$command" -t "$tutorial" --docker \
                | ansifilter | tee "$LOG_DIR/$tutorial.$command.docker-used.log"
        done
    done
}


main "$@"
