#!/bin/sh -eu


FIRST_RUN="first run"


main()
{
    echo "$FIRST_RUN" | run_cabal_per_line "$@"
    wait_for_change \
        | filter_unrelated_out \
        | run_cabal_per_line "$@"
}

wait_for_change()
{
    fswatch -rdaE -l .5 -e '/\.' \
        --event Updated --event Removed . 2>/dev/null
}

filter_unrelated_out()
{
    grep -E '/[^.#][^/]*\.(hs|lhs|cabal)$' --line-buffered \
        | grep -E -v --line-buffered '(/dist-newstyle/|/flycheck_)'
}

run_cabal_per_line()
{
    last_hash=""
    while read -r file_triggering
    do
        new_hash="$(
            md5sum "$file_triggering" 2> /dev/null \
                || echo "$last_hash")"
        if [ "$new_hash" != "$last_hash" ] \
            || [ "$file_triggering" = "$FIRST_RUN" ]
        then
            printf '\nTRIGGER: %s\n' "$file_triggering"
            last_hash="$new_hash"
            if output="$(run_cabal "$@")"
            then
                printf '\033[34m%s: SUCCESS\033[m\n' "$(date)"
            else
                printf '\n\033[31m%s\033[m\n' "$output"
                printf '\n\033[1;31m%s: ERROR\033[m\n' "$(date)"
            fi
        fi
    done
}

run_cabal()
{
    cabal new-build "$@" 3>&2 2>&1 1>&3
}


main "$@"
