#+TITLE: Extn-Python Spacemacs Layer
#+SETUPFILE: ../../../../internal/setup.org

* About Extn-Python Spacemacs Layer

  This layer extends the Spacemacs-provided =python= layer with just an extra
  keystroke and command to restart the Anaconda server. This restart also picks
  up Direnv environment changes via the [[emacs-direnv][emacs-direnv]] Emacs package if enabled.

  That's all it does for now. Otherwise, it just turns on the =python= layer
  for you, see [[spacemacs-python][that layer's official documentation]] for more information.

* Installation

** Dependencies

   Spacemacs's =python= layer naturally requires an installation of Python, but
   also provides support for a variety of Python static analysis tools and test
   runners.

   We want our development experiences to be stable and portable from machine
   to machine, so it's nice to have project-level Nix expressions provide
   project-level dependencies. [[../../../../pkgs-make/README.org][Pkgs-make]] can do this by providing our Python
   interpretter and development tools for a =nix-shell= session. Nix shell
   environment variables can be integrated into Direnv with the [[../../../direnv/README.org][Direnv support
   provided]] as well as [[../../../oh-my-zsh/README.org][Oh-My-ZSH integration]]. To tie this back to Spacemacs,
   you can use the [[../direnv/README.org][provided =direnv= Spacemacs layer]].

   Otherwise, you can install any dependencies using an OS package manager like
   Nix.

** Enabling the layer

   To use this configuration layer, copy or link this layer's =extn-python=
   directory to the private layers directory of your Spacemacs installation
   keeping the name (=~/.emacs.d/private/extn-python=).

   Then enable it in your =~/.spacemacs=:

   #+BEGIN_SRC emacs-lisp :eval no
     (defun dotspacemacs/layers ()
       (setq-default
          ;; ... other configuration ...
        dotspacemacs-configuration-layers
          '( ; ... other layers
            extn-python)))
   #+END_SRC

* Features/Configuration

** Key bindings

*** From the =python= Spacemacs layer

    Many key binds come from the =python= layer. Rather than redocument those
    bindings here, see the [[spacemacs-python-bindings][documentation for that layer]].

*** From this layer

    There's just one command/keybinding we provide:

    | Key Binding | Command                             | Description                                             |
    |-------------+-------------------------------------+---------------------------------------------------------|
    | ~SPC m , a~ | ~extn-python/anaconda-mode-restart~ | restart anaconda-server, updating direnv if appropriate |

    We could kill the =*anaconda-mode*= buffer to restart the background
    process, but that's a bit annoying to do without a key binding.
    =anaconda-mode= tries to intelligently restart itself, which is why they
    probably don't offer a keybinding for manually restarting.

    Additionally, =anaconda-mode= is not aware of when environment variables
    change from packages like =emacs-direnv=. So our new command also update
    the Direnv environment variable before restarting the server.
