#!/usr/bin/env bash

print_array() {
for a in "$@"
do echo -n [$a]
done
echo
}

update_array() {
    local -n arr=my_array
    arr+=("two three" four)
}

use_array_a() {
    local my_array=(a)
    use_array_b
    update_array my_array
    print_array "${my_array[@]}"
}

use_array_b() {
    local my_array=(b)
    update_array my_array
    print_array "${my_array[@]}"
}

use_array_a
use_array_b
