#!/bin/sh -eu


. "$(dirname "$0")/common.sh"


#BUILD_IMAGE="nixorg/nix:1"
BUILD_IMAGE="nixpkgs/nix:nixos-20.03"
VOLUME_ROOT="nix-package-home"
VOLUME_NIX="nix-package-cache"

REPO_ROOT="$(repository_root "$0")"


main()
(
    create_volume_if_missing "$VOLUME_ROOT" /root
    create_volume_if_missing "$VOLUME_NIX" /nix
    run_in_docker "$@"
)

create_volume_if_missing()
(
    volume="$1"
    source="$2"
    if ! volume_exists "$volume"
    then create_volume "$volume" "$source"
    fi
)

run_in_docker()
{
    do_with_header docker run \
        --rm \
        --interactive \
        --tty \
        --env PATH=/bin:/usr/bin:/mnt/run \
        --volume "$(abspath "$REPO_ROOT"):/mnt" \
        --volume "$VOLUME_ROOT:/root" \
        --volume "$VOLUME_NIX:/nix" \
        --volume "/var/run/docker.sock:/var/run/docker.sock" \
        --workdir /mnt \
        "$BUILD_IMAGE" \
        "$@"
}

volume_exists()
(
    volume="$1"
    docker inspect "$volume" 1>/dev/null 2>/dev/null
)

create_volume()
(
    volume="$1"
    source="$2"
    do_with_header docker volume create "$volume"
    do_with_header docker run --rm -v "$volume:/mnt" "$BUILD_IMAGE" \
        cp -a -T "$source" /mnt
)


main "$@"
