#!/bin/sh -eu

cd "$(dirname "$0")"

exec nix run \
    --show-trace \
    --ignore-environment \
    --keep LANG \
    --keep TERM \
    --keep SSL_CERT_FILE \
    --file nix \
    run.unified \
    --command \
    nix-package-run \
    --nix \
    "$(command -v nix)" \
    "$@"
