#!/bin/sh -eu


USAGE="
Synopsis:

    tags generator for all Haskell projects found recursively from the current
    directory, tailored for a Nix-shell environment

Usage: nix-tags-haskell [OPTION...]

Options:

    -c, --ctags
        generate ctags file

    -e, --etags
        generate etags file

    -b, --both
        generate both ctags and etags file (default)

    -x, --extendedctag
        extend format for ctag

    -a, --append
        append tags files (sorting lost)

    --ignore-close-implementation
        ignores implementation closer than 7 lines

    -R, --tags-absolute
        make tags absolute paths

    -h, --help
        output this help message and exit
"


for arg in "$@"
do
    case "$arg" in
        -h|--help)
            echo "$USAGE"
            exit 0
            ;;
    esac
done


haskdogs \
    --use-stack OFF \
    -- \
    --follow-symlinks \
    "$@"
