#+TITLE: Direnv Spacemacs Layer
#+SETUPFILE: ../../../../support/links.org

* About Direnv Spacemacs Layer

  This layer provides [[emacs-direnv][emacs-direnv]]/[[direnv][Direnv]] integration for managing different
  sets of environment variables for different directories.

  This allows, for example, the executables on the =PATH= for one Emacs buffer
  to be different from another one. One project might use one version of a
  compiler. Another one might use another installed elsewhere.

  With Direnv, we need a lot less language-platform specific configuration with
  Emacs packages or Spacemacs layers. We just set up the environment the way we
  want for the command line, and Emacs just picks it up per-buffer. We don't
  need to launch Emacs from a special environment that only works for certain
  projects. So direnv is much friendly for Emacs in daemon mode.

  This layer just sets up a few key bindings and delegates to emacs-direnv.

* Installation

** Dependencies

   You need the =direnv= executable on your =PATH=. There are [[direnv-install][many ways to get
   it]].

** Enabling the layer

   To use this configuration layer, copy or link this layer's =direnv=
   directory to the private layers directory of your Spacemacs installation
   keeping the name (=~/.emacs.d/private/direnv=).

   Then enable it in your =~/.spacemacs=:

   #+BEGIN_SRC emacs-lisp :eval no
     (defun dotspacemacs/layers ()
       (setq-default
          ;; ... other configuration ...
        dotspacemacs-configuration-layers
          '( ; ... other layers
            direnv)))
   #+END_SRC

* Features/Configuration

  Some useful Direnv Emacs commands have key bindings under the prefix ~SPC d~:

  | Key Binding | Command                               | Description                                       |
  |-------------+---------------------------------------+---------------------------------------------------|
  | ~SPC d e~   | ~direnv-edit~                         | edit the relevant .envrc file for the buffer      |
  | ~SPC d d~   | ~direnv-update-environment~           | update the environment from direnv for the buffer |
  | ~SPC d u~   | ~direnv-update-directory-environment~ | update the environment for the buffer's directory |

  See the [[emacs-direnv-usage][emacs-direnv documentation]] for more information.
